name: 📊 GitHub Metrics

on:
  schedule:
    - cron: '0 1 * * *' # every day at 01:00 UTC
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: nholuongut
          filename: metrics.svg
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Ho_Chi_Minh
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_followup: yes
          plugin_traffic: yes
