name: ♻️ Auto Refresh GitHub Stats

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update README (trigger stats cache refresh)
        run: |
          sed -i "s|<!-- auto-refresh -->.*<!-- /auto-refresh -->|<!-- auto-refresh --> Updated on $(date -u +'%Y-%m-%dT%H:%M:%SZ') <!-- /auto-refresh -->|" README.md

      - name: Commit Changes
        run: |
          git config --global user.name "nholuongut"
          git config --global user.email "luongutnho.dxc@gmail.com"
          git commit -am "chore: auto-refresh GitHub stats"
          git push
