jobs:
  open-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%B %d, %Y')" >> "$GITHUB_OUTPUT"

      - name: Create weekly issue
        uses: dacbd/create-issue-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Weekly Check-In: ${{ steps.date.outputs.date }}"
          body: |
            This is your automatic weekly issue to track contributions.
            - [ ] Comment something!
            - [ ] Close when done.
